"""Unit tests for ``agentic_audit.layer2_narrative.generator``.

Mocks the Azure OpenAI client entirely — no live calls, no
``azure-identity`` dependency required at test time. The live
round-trip is exercised by
``tests/integration/test_layer2_generator_e2e.py``
(``@pytest.mark.slow``, env-gated).

This file covers the **first commit-able artefact** of step_05_task_03:
construction + smoke-chat dispatch. Subsequent commits within the
task_03 PR will add tests for prompt rendering, runtime guard against
non-narratable attributes, word-limit retry, and the full
``generate(...)`` flow.
"""

from __future__ import annotations

from unittest.mock import MagicMock

import pytest

from agentic_audit.layer2_narrative.generator import (
    AZURE_OPENAI_API_VERSION,
    NarrativeGenerator,
)

# ---------- pinned constants -------------------------------------------


def test_api_version_is_pinned_to_2024_10_21() -> None:
    """The pinned API version must support response_format JSON mode,
    which the full generator (subsequent commits) will rely on. If
    this version moves, validate JSON-mode behaviour against the new
    version before bumping."""
    assert AZURE_OPENAI_API_VERSION == "2024-10-21"


# ---------- construction -----------------------------------------------


def test_init_with_explicit_client_does_not_build_one() -> None:
    """When a client is dependency-injected, the constructor must NOT
    invoke the live azure-identity / openai factory. This is what
    makes the tests runnable without those libraries actually
    constructing a real credential.
    """
    fake_client = MagicMock()
    gen = NarrativeGenerator(
        endpoint="https://aoai-aaf-dev.openai.azure.com/",
        deployment="gpt-4o",
        prompt_version="v1.0",
        client=fake_client,
    )
    assert gen.endpoint == "https://aoai-aaf-dev.openai.azure.com/"
    assert gen.deployment == "gpt-4o"
    assert gen.prompt_version == "v1.0"
    # Internal client is exactly what we passed in
    assert gen._client is fake_client


def test_init_pins_prompt_version_at_construction_time() -> None:
    """Pinning at init means downstream narratives generated by THIS
    instance all carry the same prompt_version. Two generators with
    different versions = two clean cohorts for A/B comparison."""
    g1 = NarrativeGenerator(
        endpoint="x", deployment="gpt-4o", prompt_version="v1.0", client=MagicMock()
    )
    g2 = NarrativeGenerator(
        endpoint="x", deployment="gpt-4o", prompt_version="v1.1", client=MagicMock()
    )
    assert g1.prompt_version == "v1.0"
    assert g2.prompt_version == "v1.1"


# ---------- from_env ---------------------------------------------------


def test_from_env_reads_endpoint_from_env_var(monkeypatch: pytest.MonkeyPatch) -> None:
    """Production wiring uses AZURE_OPENAI_ENDPOINT. Verify the factory
    reads it correctly. A fake client is patched into the construction
    path so this test does not need azure-identity / openai installed
    at import-resolve time."""
    monkeypatch.setenv("AZURE_OPENAI_ENDPOINT", "https://test-endpoint.example.com/")
    monkeypatch.setattr(
        "agentic_audit.layer2_narrative.generator._build_azure_openai_client",
        lambda **kwargs: MagicMock(name="FakeAzureOpenAI"),
    )

    gen = NarrativeGenerator.from_env()

    assert gen.endpoint == "https://test-endpoint.example.com/"
    assert gen.deployment == "gpt-4o"  # default
    assert gen.prompt_version == "v1.0"  # default


def test_from_env_uses_explicit_overrides(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AZURE_OPENAI_ENDPOINT", "https://other.example.com/")
    monkeypatch.setattr(
        "agentic_audit.layer2_narrative.generator._build_azure_openai_client",
        lambda **kwargs: MagicMock(),
    )

    gen = NarrativeGenerator.from_env(deployment="gpt-4o-mini", prompt_version="v1.1")

    assert gen.deployment == "gpt-4o-mini"
    assert gen.prompt_version == "v1.1"


def test_from_env_raises_when_endpoint_unset(monkeypatch: pytest.MonkeyPatch) -> None:
    """Missing endpoint env var → loud, helpful error. We do NOT silently
    fall back to a default endpoint — that would mask production
    misconfiguration."""
    monkeypatch.delenv("AZURE_OPENAI_ENDPOINT", raising=False)
    with pytest.raises(RuntimeError, match="AZURE_OPENAI_ENDPOINT"):
        NarrativeGenerator.from_env()


def test_from_env_with_custom_env_var_name(monkeypatch: pytest.MonkeyPatch) -> None:
    """Some test setups may use a different env var name; the factory
    accepts an override."""
    monkeypatch.delenv("AZURE_OPENAI_ENDPOINT", raising=False)
    monkeypatch.setenv("MY_CUSTOM_ENDPOINT", "https://custom.example.com/")
    monkeypatch.setattr(
        "agentic_audit.layer2_narrative.generator._build_azure_openai_client",
        lambda **kwargs: MagicMock(),
    )

    gen = NarrativeGenerator.from_env(endpoint_env_var="MY_CUSTOM_ENDPOINT")
    assert gen.endpoint == "https://custom.example.com/"


# ---------- _smoke_chat ------------------------------------------------


def test_smoke_chat_passes_deployment_as_model_argument() -> None:
    """Azure OpenAI's chat.completions.create takes the DEPLOYMENT name
    in the ``model`` kwarg (not the underlying model id like 'gpt-4').
    Getting this wrong is the most common Azure-vs-OpenAI footgun."""
    fake_client = MagicMock()
    gen = NarrativeGenerator(
        endpoint="x",
        deployment="gpt-4o",
        prompt_version="v1.0",
        client=fake_client,
    )

    gen._smoke_chat()

    fake_client.chat.completions.create.assert_called_once()
    kwargs = fake_client.chat.completions.create.call_args.kwargs
    assert kwargs["model"] == "gpt-4o"  # the DEPLOYMENT name
    assert kwargs["temperature"] == 0
    assert kwargs["max_tokens"] == 8


def test_smoke_chat_default_user_message_asks_for_ok() -> None:
    """Default smoke message is deterministic and short. The integration
    test asserts on 'OK' in the response — keep this default in sync
    with that assertion."""
    fake_client = MagicMock()
    gen = NarrativeGenerator(
        endpoint="x", deployment="gpt-4o", prompt_version="v1.0", client=fake_client
    )

    gen._smoke_chat()

    messages = fake_client.chat.completions.create.call_args.kwargs["messages"]
    assert len(messages) == 1
    assert messages[0]["role"] == "user"
    assert "OK" in messages[0]["content"]


def test_smoke_chat_custom_user_message_is_forwarded() -> None:
    fake_client = MagicMock()
    gen = NarrativeGenerator(
        endpoint="x", deployment="gpt-4o", prompt_version="v1.0", client=fake_client
    )

    gen._smoke_chat(user_message="ping")

    messages = fake_client.chat.completions.create.call_args.kwargs["messages"]
    assert messages[0]["content"] == "ping"


def test_smoke_chat_returns_underlying_response_object() -> None:
    """The method does not unpack the response — caller asserts on
    .choices[0].message.content. This keeps the smoke method generic
    and lets callers inspect tokens / finish_reason / etc."""
    fake_response = MagicMock(name="ChatCompletion")
    fake_client = MagicMock()
    fake_client.chat.completions.create.return_value = fake_response
    gen = NarrativeGenerator(
        endpoint="x", deployment="gpt-4o", prompt_version="v1.0", client=fake_client
    )

    result = gen._smoke_chat()

    assert result is fake_response
