"""Unit tests for ``agentic_audit.layer2_narrative.generator``.

Mocks the Azure OpenAI client entirely — no live calls, no
``azure-identity`` dependency required at test time. The live
round-trip is exercised by
``tests/integration/test_layer2_generator_e2e.py``
(``@pytest.mark.slow``, env-gated).

This file covers the **first commit-able artefact** of step_05_task_03:
construction + smoke-chat dispatch. Subsequent commits within the
task_03 PR will add tests for prompt rendering, runtime guard against
non-narratable attributes, word-limit retry, and the full
``generate(...)`` flow.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from unittest.mock import MagicMock

import pytest

from agentic_audit.layer2_narrative.generator import (
    AZURE_OPENAI_API_VERSION,
    NarrativeGenerator,
)
from agentic_audit.models.evidence import (
    AttributeCheck,
    ExtractedEvidence,
    SignOff,
)
from agentic_audit.models.narrative import AttributeNarrative

UTC_TS = datetime(2026, 5, 5, 12, 0, 0, tzinfo=UTC)

# ---------- pinned constants -------------------------------------------


def test_api_version_is_pinned_to_2024_10_21() -> None:
    """The pinned API version must support response_format JSON mode,
    which the full generator (subsequent commits) will rely on. If
    this version moves, validate JSON-mode behaviour against the new
    version before bumping."""
    assert AZURE_OPENAI_API_VERSION == "2024-10-21"


# ---------- construction -----------------------------------------------


def test_init_with_explicit_client_does_not_build_one() -> None:
    """When a client is dependency-injected, the constructor must NOT
    invoke the live azure-identity / openai factory. This is what
    makes the tests runnable without those libraries actually
    constructing a real credential.
    """
    fake_client = MagicMock()
    gen = NarrativeGenerator(
        endpoint="https://aoai-aaf-dev.openai.azure.com/",
        deployment="gpt-4o",
        prompt_version="v1.0",
        client=fake_client,
    )
    assert gen.endpoint == "https://aoai-aaf-dev.openai.azure.com/"
    assert gen.deployment == "gpt-4o"
    assert gen.prompt_version == "v1.0"
    # Internal client is exactly what we passed in
    assert gen._client is fake_client


def test_init_pins_prompt_version_at_construction_time() -> None:
    """Pinning at init means downstream narratives generated by THIS
    instance all carry the same prompt_version. Two generators with
    different versions = two clean cohorts for A/B comparison."""
    g1 = NarrativeGenerator(
        endpoint="x", deployment="gpt-4o", prompt_version="v1.0", client=MagicMock()
    )
    g2 = NarrativeGenerator(
        endpoint="x", deployment="gpt-4o", prompt_version="v1.1", client=MagicMock()
    )
    assert g1.prompt_version == "v1.0"
    assert g2.prompt_version == "v1.1"


# ---------- from_env ---------------------------------------------------


def test_from_env_reads_endpoint_from_env_var(monkeypatch: pytest.MonkeyPatch) -> None:
    """Production wiring uses AZURE_OPENAI_ENDPOINT. Verify the factory
    reads it correctly. A fake client is patched into the construction
    path so this test does not need azure-identity / openai installed
    at import-resolve time."""
    monkeypatch.setenv("AZURE_OPENAI_ENDPOINT", "https://test-endpoint.example.com/")
    monkeypatch.setattr(
        "agentic_audit.layer2_narrative.generator._build_azure_openai_client",
        lambda **kwargs: MagicMock(name="FakeAzureOpenAI"),
    )

    gen = NarrativeGenerator.from_env()

    assert gen.endpoint == "https://test-endpoint.example.com/"
    assert gen.deployment == "gpt-4o"  # default
    # Default bumped v1.0 → v1.1 once the v1.1 final baseline became canonical
    # (2026-05-11). v1.0 is still runnable via explicit override (see next test).
    assert gen.prompt_version == "v1.1"


def test_from_env_uses_explicit_overrides(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AZURE_OPENAI_ENDPOINT", "https://other.example.com/")
    monkeypatch.setattr(
        "agentic_audit.layer2_narrative.generator._build_azure_openai_client",
        lambda **kwargs: MagicMock(),
    )

    gen = NarrativeGenerator.from_env(deployment="gpt-4o-mini", prompt_version="v1.1")

    assert gen.deployment == "gpt-4o-mini"
    assert gen.prompt_version == "v1.1"


def test_from_env_raises_when_endpoint_unset(monkeypatch: pytest.MonkeyPatch) -> None:
    """Missing endpoint env var → loud, helpful error. We do NOT silently
    fall back to a default endpoint — that would mask production
    misconfiguration."""
    monkeypatch.delenv("AZURE_OPENAI_ENDPOINT", raising=False)
    with pytest.raises(RuntimeError, match="AZURE_OPENAI_ENDPOINT"):
        NarrativeGenerator.from_env()


def test_from_env_with_custom_env_var_name(monkeypatch: pytest.MonkeyPatch) -> None:
    """Some test setups may use a different env var name; the factory
    accepts an override."""
    monkeypatch.delenv("AZURE_OPENAI_ENDPOINT", raising=False)
    monkeypatch.setenv("MY_CUSTOM_ENDPOINT", "https://custom.example.com/")
    monkeypatch.setattr(
        "agentic_audit.layer2_narrative.generator._build_azure_openai_client",
        lambda **kwargs: MagicMock(),
    )

    gen = NarrativeGenerator.from_env(endpoint_env_var="MY_CUSTOM_ENDPOINT")
    assert gen.endpoint == "https://custom.example.com/"


# ---------- _smoke_chat ------------------------------------------------


def test_smoke_chat_passes_deployment_as_model_argument() -> None:
    """Azure OpenAI's chat.completions.create takes the DEPLOYMENT name
    in the ``model`` kwarg (not the underlying model id like 'gpt-4').
    Getting this wrong is the most common Azure-vs-OpenAI footgun."""
    fake_client = MagicMock()
    gen = NarrativeGenerator(
        endpoint="x",
        deployment="gpt-4o",
        prompt_version="v1.0",
        client=fake_client,
    )

    gen._smoke_chat()

    fake_client.chat.completions.create.assert_called_once()
    kwargs = fake_client.chat.completions.create.call_args.kwargs
    assert kwargs["model"] == "gpt-4o"  # the DEPLOYMENT name
    assert kwargs["temperature"] == 0
    assert kwargs["max_tokens"] == 8


def test_smoke_chat_default_user_message_asks_for_ok() -> None:
    """Default smoke message is deterministic and short. The integration
    test asserts on 'OK' in the response — keep this default in sync
    with that assertion."""
    fake_client = MagicMock()
    gen = NarrativeGenerator(
        endpoint="x", deployment="gpt-4o", prompt_version="v1.0", client=fake_client
    )

    gen._smoke_chat()

    messages = fake_client.chat.completions.create.call_args.kwargs["messages"]
    assert len(messages) == 1
    assert messages[0]["role"] == "user"
    assert "OK" in messages[0]["content"]


def test_smoke_chat_custom_user_message_is_forwarded() -> None:
    fake_client = MagicMock()
    gen = NarrativeGenerator(
        endpoint="x", deployment="gpt-4o", prompt_version="v1.0", client=fake_client
    )

    gen._smoke_chat(user_message="ping")

    messages = fake_client.chat.completions.create.call_args.kwargs["messages"]
    assert messages[0]["content"] == "ping"


def test_smoke_chat_returns_underlying_response_object() -> None:
    """The method does not unpack the response — caller asserts on
    .choices[0].message.content. This keeps the smoke method generic
    and lets callers inspect tokens / finish_reason / etc."""
    fake_response = MagicMock(name="ChatCompletion")
    fake_client = MagicMock()
    fake_client.chat.completions.create.return_value = fake_response
    gen = NarrativeGenerator(
        endpoint="x", deployment="gpt-4o", prompt_version="v1.0", client=fake_client
    )

    result = gen._smoke_chat()

    assert result is fake_response


# ---------- generate() — runtime guard ---------------------------------


def _make_evidence(
    *,
    control_id: str = "DC-9",
    quarter: str = "Q1",
    attribute_ids: list[str] | None = None,
) -> ExtractedEvidence:
    """Build an ExtractedEvidence with sane defaults."""
    if attribute_ids is None:
        attribute_ids = (
            ["A", "B", "C", "D", "E", "F"] if control_id == "DC-9" else ["A", "B", "C", "D"]
        )
    attrs = [
        AttributeCheck(
            control_id=control_id,  # type: ignore[arg-type]
            attribute_id=a,  # type: ignore[arg-type]
            status="pass",
            evidence_cell_refs=[f"{control_id.replace('-', '')}_WP!{a}1"],
            extracted_value={"sample": f"val-{a}"},
            notes=f"check {a}",
        )
        for a in attribute_ids
    ]
    return ExtractedEvidence(
        engagement_id="alpha-pension-fund-2025",
        control_id=control_id,  # type: ignore[arg-type]
        quarter=quarter,  # type: ignore[arg-type]
        run_id="01J0F7M5XQXM2QYAY8X8X8X8X8",
        extraction_timestamp=UTC_TS,
        preparer=SignOff(initials="AB", role="preparer", date=UTC_TS),
        reviewer=SignOff(initials="CD", role="reviewer", date=UTC_TS),
        attributes=attrs,
        source_bronze_file_hash="a" * 64,
        source_path=f"/bronze/dc{control_id.split('-')[1]}_{quarter}_ref.xlsx",
    )


def _build_chat_completion_response(
    narrative_text: str,
    cited_fields: list[str] | None = None,
    word_count: int | None = None,
) -> MagicMock:
    """Mock an OpenAI ChatCompletion that yields the given JSON body."""
    if cited_fields is None:
        cited_fields = ["DC9_WP!A1"]
    if word_count is None:
        word_count = len(narrative_text.split())
    payload = json.dumps(
        {
            "narrative_text": narrative_text,
            "cited_fields": cited_fields,
            "word_count": word_count,
        }
    )
    response = MagicMock()
    response.choices = [MagicMock()]
    response.choices[0].message.content = payload
    response.choices[0].finish_reason = "stop"
    return response


def _make_generator(client: MagicMock) -> NarrativeGenerator:
    return NarrativeGenerator(
        endpoint="https://aoai-aaf-rbpal-dev.openai.azure.com/",
        deployment="gpt-4o",
        prompt_version="v1.0",
        client=client,
    )


def test_generate_rejects_dc9_attribute_d_reserved_for_layer3() -> None:
    """DC-9.D is the Layer 3 React-loop attribute (rate change with
    amendment plausibility). The narrative generator must NOT accept
    it — runtime guard fires before any LLM call."""
    fake_client = MagicMock()
    gen = _make_generator(fake_client)

    with pytest.raises(ValueError, match="not narratable for 'DC-9'"):
        gen.generate("D", _make_evidence(control_id="DC-9"))

    fake_client.chat.completions.create.assert_not_called()


def test_generate_rejects_dc2_attribute_b_reserved_for_layer3() -> None:
    """DC-2.B is the Layer 3 React-loop attribute (variance explanation
    plausibility). Same guard applies."""
    fake_client = MagicMock()
    gen = _make_generator(fake_client)

    with pytest.raises(ValueError, match="not narratable for 'DC-2'"):
        gen.generate("B", _make_evidence(control_id="DC-2"))

    fake_client.chat.completions.create.assert_not_called()


def test_generate_runtime_guard_error_message_includes_remediation() -> None:
    """Error message must point at Decision 2 in the doc + name the
    Layer 3 reserved set, so the caller can fix the call site."""
    fake_client = MagicMock()
    gen = _make_generator(fake_client)

    with pytest.raises(ValueError) as exc:
        gen.generate("B", _make_evidence(control_id="DC-2"))

    msg = str(exc.value)
    assert "narratable" in msg
    assert "Decision 2" in msg
    assert "step_05_layer2_narrative.md" in msg
    assert "Reserved for Layer 3" in msg


# ---------- generate() — happy path ------------------------------------


def test_generate_dc9_attribute_a_returns_attribute_narrative() -> None:
    """Happy path: 30-word narrative under the limit. Returns a fully
    populated AttributeNarrative."""
    narrative = "Preparer AB signed DC-9.A on 2026-05-03 (see DC9_WP!A1)."
    fake_client = MagicMock()
    fake_client.chat.completions.create.return_value = _build_chat_completion_response(narrative)
    gen = _make_generator(fake_client)

    result = gen.generate("A", _make_evidence(control_id="DC-9"))

    assert isinstance(result, AttributeNarrative)
    assert result.engagement_id == "alpha-pension-fund-2025"
    assert result.control_id == "DC-9"
    assert result.attribute_id == "A"
    assert result.quarter == "Q1"
    assert result.narrative_text == narrative
    assert result.cited_fields == ["DC9_WP!A1"]
    assert result.word_count == len(narrative.split())
    assert result.prompt_version == "v1.0"
    assert result.model_deployment == "gpt-4o"
    assert result.generation_run_id  # auto-minted, non-empty
    assert result.fact_check_passed is False  # default, awaiting fact-checker
    assert result.fact_check_issues == []


def test_generate_dc2_attribute_a_works_with_dc2_narratable_set() -> None:
    """DC-2 narratable set is {A, C, D}. Verify A passes the guard
    (asymmetric reservation per Decision 2 — different from DC-9)."""
    narrative = "Data-load tie-out matched feed and workbook totals (see DC2_WP!A1)."
    fake_client = MagicMock()
    fake_client.chat.completions.create.return_value = _build_chat_completion_response(narrative)
    gen = _make_generator(fake_client)

    result = gen.generate("A", _make_evidence(control_id="DC-2"))

    assert result.control_id == "DC-2"
    assert result.attribute_id == "A"


def test_generate_uses_caller_supplied_run_id() -> None:
    """Sweep scripts pass a shared run_id so all narratives in one
    sweep form a coherent cohort."""
    fake_client = MagicMock()
    fake_client.chat.completions.create.return_value = _build_chat_completion_response("short")
    gen = _make_generator(fake_client)

    result = gen.generate(
        "A", _make_evidence(control_id="DC-9"), generation_run_id="SWEEP-2026-05-05-001"
    )

    assert result.generation_run_id == "SWEEP-2026-05-05-001"


def test_generate_mints_unique_run_ids_when_caller_does_not_supply_one() -> None:
    """Two ad-hoc generate() calls without a run_id should get
    different ids — no collision between unrelated invocations."""
    fake_client = MagicMock()
    fake_client.chat.completions.create.return_value = _build_chat_completion_response("short")
    gen = _make_generator(fake_client)
    evidence = _make_evidence(control_id="DC-9")

    r1 = gen.generate("A", evidence)
    r2 = gen.generate("A", evidence)

    assert r1.generation_run_id != r2.generation_run_id


def test_generate_source_evidence_id_is_natural_key() -> None:
    """source_evidence_id should be the same shape silver.evidence's
    MERGE key uses — engagement|control|attribute|quarter."""
    fake_client = MagicMock()
    fake_client.chat.completions.create.return_value = _build_chat_completion_response("short")
    gen = _make_generator(fake_client)

    result = gen.generate("A", _make_evidence(control_id="DC-9", quarter="Q1"))

    assert result.source_evidence_id == "alpha-pension-fund-2025|DC-9|A|Q1"


# ---------- generate() — LLM call shape --------------------------------


def test_generate_calls_llm_with_json_mode_and_max_tokens() -> None:
    """The chat completion must be called with response_format={
    type: json_object }, temperature=0, and max_tokens=500.

    The 500 limit was raised from 300 in step_05_task_08 after the
    first task_07 sweep showed 5 of 32 combinations hit ``Unterminated
    string`` JSONDecodeError because the LLM was running out of
    tokens before closing the JSON envelope. 500 gives ~250 tokens
    of headroom over the 150-word narrative + cited_fields array."""
    fake_client = MagicMock()
    fake_client.chat.completions.create.return_value = _build_chat_completion_response("short")
    gen = _make_generator(fake_client)

    gen.generate("A", _make_evidence(control_id="DC-9"))

    kwargs = fake_client.chat.completions.create.call_args.kwargs
    assert kwargs["model"] == "gpt-4o"  # deployment name, not model id
    assert kwargs["temperature"] == 0
    assert kwargs["max_tokens"] == 500
    assert kwargs["response_format"] == {"type": "json_object"}


def test_generate_prompt_contains_evidence_envelope_and_attribute_check() -> None:
    """The rendered prompt must include the evidence envelope (control,
    attribute, quarter) AND the per-attribute check details. If the
    prompt drops either, the LLM doesn't have enough grounding context."""
    fake_client = MagicMock()
    fake_client.chat.completions.create.return_value = _build_chat_completion_response("short")
    gen = _make_generator(fake_client)

    gen.generate("A", _make_evidence(control_id="DC-9"))

    prompt = fake_client.chat.completions.create.call_args.kwargs["messages"][0]["content"]
    # Envelope substituted
    assert "CONTROL: DC-9" in prompt
    assert "ATTRIBUTE: A" in prompt
    assert "QUARTER: Q1" in prompt
    # Evidence JSON contains the attribute_check payload
    assert "attribute_check" in prompt
    assert "DC9_WP!A1" in prompt
    # Envelope (preparer / reviewer / source lineage) carried
    assert "preparer" in prompt
    assert "alpha-pension-fund-2025" in prompt
    # No leftover ${} placeholders — every substitution resolved
    assert "${" not in prompt


# ---------- generate() — empty / malformed LLM response ----------------


def test_generate_raises_on_empty_response_content() -> None:
    """If the LLM returns empty content, raise loudly with finish_reason
    in the message — that's diagnostic (e.g., 'length' = max_tokens hit)."""
    fake_response = MagicMock()
    fake_response.choices = [MagicMock()]
    fake_response.choices[0].message.content = None
    fake_response.choices[0].finish_reason = "length"
    fake_client = MagicMock()
    fake_client.chat.completions.create.return_value = fake_response
    gen = _make_generator(fake_client)

    with pytest.raises(ValueError, match="empty response.*finish_reason"):
        gen.generate("A", _make_evidence(control_id="DC-9"))


def test_generate_retries_once_on_malformed_json_then_raises() -> None:
    """JSON mode occasionally emits invalid JSON despite the
    response_format constraint. ``_invoke_llm`` retries once with the
    same prompt; if the second attempt also fails to parse, raises a
    ValueError with the raw content embedded for debugging.

    Calibration learnt from the step_05_task_07 sweep — 5 of 32
    combinations hit JSONDecodeError; one retry recovers the
    transient subset, the persistent subset gets surfaced loudly."""
    fake_response = MagicMock()
    fake_response.choices = [MagicMock()]
    fake_response.choices[0].message.content = "not JSON at all"
    fake_response.choices[0].finish_reason = "stop"
    fake_client = MagicMock()
    fake_client.chat.completions.create.return_value = fake_response
    gen = _make_generator(fake_client)

    with pytest.raises(ValueError, match="malformed JSON.*both attempts"):
        gen.generate("A", _make_evidence(control_id="DC-9"))

    # Two LLM calls — one initial + one retry
    assert fake_client.chat.completions.create.call_count == 2


def test_generate_recovers_when_json_parses_on_retry() -> None:
    """If the first attempt returns garbage but the second returns
    valid JSON, the retry succeeds and the caller never sees an
    error. Models the realistic non-determinism even at temperature=0."""
    bad_response = MagicMock()
    bad_response.choices = [MagicMock()]
    bad_response.choices[0].message.content = "garbage not JSON"
    bad_response.choices[0].finish_reason = "stop"

    good_response = _build_chat_completion_response("short narrative ok")

    fake_client = MagicMock()
    fake_client.chat.completions.create.side_effect = [bad_response, good_response]
    gen = _make_generator(fake_client)

    result = gen.generate("A", _make_evidence(control_id="DC-9"))

    assert result.narrative_text == "short narrative ok"
    # Confirms the retry path was actually exercised
    assert fake_client.chat.completions.create.call_count == 2


def test_generate_raises_on_response_missing_required_fields() -> None:
    """If the LLM returns valid JSON but the wrong schema (missing
    required NarrativeResponse fields), pydantic's ValidationError fires
    at parse time."""
    fake_response = MagicMock()
    fake_response.choices = [MagicMock()]
    fake_response.choices[0].message.content = json.dumps(
        {"narrative_text": "x"}  # missing word_count
    )
    fake_response.choices[0].finish_reason = "stop"
    fake_client = MagicMock()
    fake_client.chat.completions.create.return_value = fake_response
    gen = _make_generator(fake_client)

    from pydantic import ValidationError

    with pytest.raises(ValidationError):
        gen.generate("A", _make_evidence(control_id="DC-9"))


# ---------- generate() — word-limit retry ------------------------------


def test_generate_returns_first_response_when_under_word_limit() -> None:
    """If first response is under WORD_LIMIT, no retry."""
    fake_client = MagicMock()
    fake_client.chat.completions.create.return_value = _build_chat_completion_response(
        "Short narrative.", word_count=2
    )
    gen = _make_generator(fake_client)

    result = gen.generate("A", _make_evidence(control_id="DC-9"))

    assert result.word_count == 2
    assert fake_client.chat.completions.create.call_count == 1


def test_generate_mints_unique_narrative_call_id_per_call() -> None:
    """Step 5 follow-up #5: every ``generate()`` call produces a fresh
    ``narrative_call_id``, even when the caller shares
    ``generation_run_id`` across the cohort.

    This is what lets gold.judge_outcomes.narrative_run_id join back to
    gold.narratives 1:1 instead of producing a sweep-scoped Cartesian
    product. The composite-key workaround in
    ``scripts/divergence_summary.sql`` Q2 only exists because
    historical v1.0 rows lack this column.
    """
    fake_client = MagicMock()
    fake_client.chat.completions.create.return_value = _build_chat_completion_response(
        "Short narrative.", word_count=2
    )
    gen = _make_generator(fake_client)
    shared_gen_id = "SWEEP_RUN_FAKE"

    result_a = gen.generate("A", _make_evidence(control_id="DC-9"), generation_run_id=shared_gen_id)
    result_b = gen.generate("C", _make_evidence(control_id="DC-9"), generation_run_id=shared_gen_id)

    # sweep-scoped id shared across the cohort
    assert result_a.generation_run_id == shared_gen_id
    assert result_b.generation_run_id == shared_gen_id
    # but per-call ids are distinct and non-None
    assert result_a.narrative_call_id is not None
    assert result_b.narrative_call_id is not None
    assert result_a.narrative_call_id != result_b.narrative_call_id
    # And distinct from the sweep id too — they share the _new_run_id
    # mint pattern but should never collide in practice.
    assert result_a.narrative_call_id != shared_gen_id


def test_generate_retries_once_when_first_response_over_limit() -> None:
    """Over-limit on first attempt → retry once with stricter prompt.
    Second response under limit → return that."""
    fake_client = MagicMock()
    long_response = _build_chat_completion_response("x " * 200, word_count=200)
    short_response = _build_chat_completion_response("short", word_count=1)
    fake_client.chat.completions.create.side_effect = [long_response, short_response]
    gen = _make_generator(fake_client)

    result = gen.generate("A", _make_evidence(control_id="DC-9"))

    assert result.word_count == 1
    assert fake_client.chat.completions.create.call_count == 2
    # Stricter retry prompt mentions the previous overrun
    second_prompt = fake_client.chat.completions.create.call_args_list[1].kwargs["messages"][0][
        "content"
    ]
    assert "200 WORDS" in second_prompt
    assert "150" in second_prompt


def test_generate_truncates_when_both_attempts_exceed_limit() -> None:
    """If both attempts overran, truncate the second response to
    WORD_LIMIT words, log WARN, return the truncated narrative."""
    fake_client = MagicMock()
    overrun_words = " ".join(f"word{i}" for i in range(180))
    overrun_response = _build_chat_completion_response(overrun_words, word_count=180)
    fake_client.chat.completions.create.side_effect = [overrun_response, overrun_response]
    gen = _make_generator(fake_client)

    result = gen.generate("A", _make_evidence(control_id="DC-9"))

    assert result.word_count == 150  # truncated to limit
    assert len(result.narrative_text.split()) == 150
    # Should preserve the prefix (deterministic truncation, not summarisation)
    assert result.narrative_text.startswith("word0 word1 word2")
    assert fake_client.chat.completions.create.call_count == 2


def test_generate_truncation_logs_warning(caplog) -> None:
    """Truncation path must emit a WARN so the eval baseline surfaces
    repeated overruns. Silent truncation = silent prompt drift."""
    fake_client = MagicMock()
    overrun = _build_chat_completion_response(" ".join("w" * 200), word_count=200)
    fake_client.chat.completions.create.side_effect = [overrun, overrun]
    gen = _make_generator(fake_client)

    import logging

    with caplog.at_level(logging.WARNING):
        gen.generate("A", _make_evidence(control_id="DC-9"))

    assert any(
        "truncating" in rec.message.lower() and rec.levelno == logging.WARNING
        for rec in caplog.records
    )


# ---------- _build_evidence_json ---------------------------------------


def test_build_evidence_json_includes_envelope_and_attribute_check() -> None:
    evidence = _make_evidence(control_id="DC-9", quarter="Q1")
    payload_str = NarrativeGenerator._build_evidence_json("A", evidence)
    payload = json.loads(payload_str)

    assert payload["engagement_id"] == "alpha-pension-fund-2025"
    assert payload["control_id"] == "DC-9"
    assert payload["attribute_id"] == "A"
    assert payload["quarter"] == "Q1"
    assert payload["preparer"]["initials"] == "AB"
    assert payload["reviewer"]["initials"] == "CD"
    assert payload["source_path"].endswith(".xlsx")
    assert payload["attribute_check"]["status"] == "pass"
    assert payload["attribute_check"]["evidence_cell_refs"] == ["DC9_WP!A1"]


def test_build_evidence_json_only_includes_target_attribute() -> None:
    """The payload must contain ONLY the attribute being narrated,
    not all attributes — burning prompt tokens on attributes the LLM
    is told to ignore is wasteful."""
    evidence = _make_evidence(control_id="DC-9")
    payload_str = NarrativeGenerator._build_evidence_json("A", evidence)
    payload = json.loads(payload_str)

    # B, C, D, E, F's notes / refs must NOT appear
    assert "DC9_WP!B1" not in payload_str
    assert "check B" not in payload_str
    # Only A's attribute_check is present
    assert payload["attribute_check"]["evidence_cell_refs"] == ["DC9_WP!A1"]
    assert payload["attribute_check"]["notes"] == "check A"


def test_build_evidence_json_raises_when_attribute_missing_from_evidence() -> None:
    """Hand-constructed test payloads can leave gaps; raise loudly
    rather than silently produce an LLM-confusing payload."""
    # ExtractedEvidence's own validator requires the full per-control set,
    # so we have to mutate after construction to simulate the gap.
    evidence = _make_evidence(control_id="DC-9")
    # Drop attribute "C" from the list to simulate a hand-built bad payload
    evidence_attrs_without_c = [a for a in evidence.attributes if a.attribute_id != "C"]
    object.__setattr__(evidence, "attributes", evidence_attrs_without_c)

    with pytest.raises(ValueError, match="not present in evidence"):
        NarrativeGenerator._build_evidence_json("C", evidence)  # type: ignore[arg-type]


# ---------- _new_run_id --------------------------------------------------


def test_new_run_id_is_unique_per_call() -> None:
    ids = {NarrativeGenerator._new_run_id() for _ in range(20)}
    assert len(ids) == 20


def test_new_run_id_is_uppercase_hex() -> None:
    run_id = NarrativeGenerator._new_run_id()
    assert run_id == run_id.upper()
    int(run_id, 16)  # parses as hex; raises if not


# ---------- usage_recorder wiring (follow-up #1: cost telemetry) ---------


def _build_chat_completion_with_usage(
    narrative_text: str,
    *,
    prompt_tokens: int,
    completion_tokens: int,
) -> MagicMock:
    """Mock an OpenAI ChatCompletion that includes a populated
    ``usage`` block. Real Azure OpenAI JSON-mode responses always
    populate ``response.usage``; the recorder relies on that."""
    response = _build_chat_completion_response(narrative_text)
    response.usage = MagicMock()
    response.usage.prompt_tokens = prompt_tokens
    response.usage.completion_tokens = completion_tokens
    response.usage.total_tokens = prompt_tokens + completion_tokens
    return response


def test_generate_records_usage_when_recorder_wired() -> None:
    """When a UsageRecorder is passed to the constructor, every LLM
    call's prompt + completion tokens accumulate on the recorder."""
    from agentic_audit.models.telemetry import UsageRecorder

    fake_client = MagicMock()
    fake_client.chat.completions.create.return_value = _build_chat_completion_with_usage(
        "short narrative ok",
        prompt_tokens=120,
        completion_tokens=40,
    )
    recorder = UsageRecorder()
    gen = NarrativeGenerator(
        endpoint="x",
        deployment="gpt-4o",
        prompt_version="v1.0",
        client=fake_client,
        usage_recorder=recorder,
    )

    gen.generate("A", _make_evidence(control_id="DC-9"))

    assert recorder.n_calls == 1
    assert recorder.prompt_tokens == 120
    assert recorder.completion_tokens == 40
    assert recorder.total_tokens == 160


def test_generate_accumulates_usage_across_word_limit_retry() -> None:
    """When the first response exceeds the word limit and a retry
    fires, BOTH calls' tokens must accumulate. The retry was a billed
    LLM call too."""
    from agentic_audit.models.telemetry import UsageRecorder

    long_text = " ".join(f"w{i}" for i in range(200))  # over 150 words
    short_text = " ".join(f"w{i}" for i in range(50))  # under 150 words

    fake_client = MagicMock()
    fake_client.chat.completions.create.side_effect = [
        _build_chat_completion_with_usage(long_text, prompt_tokens=100, completion_tokens=300),
        _build_chat_completion_with_usage(short_text, prompt_tokens=120, completion_tokens=80),
    ]
    recorder = UsageRecorder()
    gen = NarrativeGenerator(
        endpoint="x",
        deployment="gpt-4o",
        prompt_version="v1.0",
        client=fake_client,
        usage_recorder=recorder,
    )

    gen.generate("A", _make_evidence(control_id="DC-9"))

    assert recorder.n_calls == 2
    assert recorder.prompt_tokens == 220
    assert recorder.completion_tokens == 380


def test_generate_accumulates_usage_across_two_generate_calls() -> None:
    """Sweep-grain recording: one recorder, multiple generate() calls,
    counts sum across the cohort."""
    from agentic_audit.models.telemetry import UsageRecorder

    fake_client = MagicMock()
    fake_client.chat.completions.create.return_value = _build_chat_completion_with_usage(
        "short ok",
        prompt_tokens=50,
        completion_tokens=20,
    )
    recorder = UsageRecorder()
    gen = NarrativeGenerator(
        endpoint="x",
        deployment="gpt-4o",
        prompt_version="v1.0",
        client=fake_client,
        usage_recorder=recorder,
    )

    gen.generate("A", _make_evidence(control_id="DC-9"))
    gen.generate("C", _make_evidence(control_id="DC-9"))

    assert recorder.n_calls == 2
    assert recorder.prompt_tokens == 100
    assert recorder.completion_tokens == 40


def test_generate_default_no_recorder_does_not_break_existing_call_sites() -> None:
    """Backwards-compatibility pin: omitting usage_recorder must not
    raise, even when the mocked response has no ``usage`` attribute
    (which is how every pre-follow-up test mock is shaped)."""
    fake_client = MagicMock()
    fake_client.chat.completions.create.return_value = _build_chat_completion_response("short ok")
    gen = NarrativeGenerator(
        endpoint="x",
        deployment="gpt-4o",
        prompt_version="v1.0",
        client=fake_client,
    )

    # No exception, no recorder side-effect — just a normal generate.
    result = gen.generate("A", _make_evidence(control_id="DC-9"))
    assert result.narrative_text == "short ok"


def test_generate_handles_response_without_usage_block_gracefully() -> None:
    """Defensive: if a future SDK / streaming-mode change drops the
    usage block, the recorder skips that call rather than crashing
    the whole sweep."""
    from agentic_audit.models.telemetry import UsageRecorder

    fake_response = _build_chat_completion_response("short ok")
    fake_response.usage = None  # simulate missing usage block

    fake_client = MagicMock()
    fake_client.chat.completions.create.return_value = fake_response
    recorder = UsageRecorder()
    gen = NarrativeGenerator(
        endpoint="x",
        deployment="gpt-4o",
        prompt_version="v1.0",
        client=fake_client,
        usage_recorder=recorder,
    )

    # Should NOT raise; should NOT record anything.
    gen.generate("A", _make_evidence(control_id="DC-9"))
    assert recorder.n_calls == 0
    assert recorder.total_tokens == 0
