terraform {
  backend "azurerm" {
    # Backend storage details (resource_group_name, storage_account_name,
    # container_name, key) are supplied at `terraform init` time via
    #   -backend-config=envs/<env>/backend.conf
    #
    # The conf file is generated by infra/bootstrap/remote_state_bootstrap.sh
    # and is gitignored at this stage. Keeping the backend type pinned here
    # but the storage details external lets dev and prod use different state
    # locations from the same root module without code duplication.
    #
    # Auth: provider falls back to the active `az login` token. For CI we
    # later switch to OIDC + service principal via ARM_USE_OIDC + the
    # standard ARM_TENANT_ID / ARM_SUBSCRIPTION_ID / ARM_CLIENT_ID vars.
  }
}
