"""Step-11 load-test analysis → ``privateDocs/load_test_results.md``.

Reads the per-scale Locust CSVs (``scale_<N>_stats.csv``) into the infra
scaling table (RPS, P50/P95/P99, failure %), and — optionally — queries App
Insights via ``az monitor log-analytics query`` for the REAL-burst cost/token
numbers (reusing the Step-10 ``AppDependencies | where Name startswith "llm."``
shape). Writes a consolidated Markdown report.

Telemetry note: observability is Azure Monitor (App Insights ``appi-aaf-dev``
backed by Log Analytics ``log-aaf-dev``), NOT Prometheus — the original Step-11
spec's Prometheus path was superseded in Step 10. Query the workspace with
``az monitor log-analytics query`` (NOT ``az monitor app-insights query``,
which can't see workspace-based data).

Usage:
  poetry run python scripts/analyze_load_test.py \
      --outdir privateDocs/load_test_results \
      [--workspace-guid 261b9176-... --burst-since 1h]
"""

from __future__ import annotations

import argparse
import csv
import glob
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass

DEFAULT_OUTDIR = "privateDocs/load_test_results"
DEFAULT_REPORT = "privateDocs/load_test_results.md"
# log-aaf-dev workspace customerId (see step_10_observability.md).
DEFAULT_WORKSPACE_GUID = "261b9176-7c3d-4c94-afe8-ee35757d26f8"


@dataclass
class ScaleRow:
    users: int
    requests: int
    failures: int
    rps: float
    p50_ms: float
    p95_ms: float
    p99_ms: float

    @property
    def failure_pct(self) -> float:
        return 100.0 * self.failures / self.requests if self.requests else 0.0


def _parse_scale_csv(path: str) -> ScaleRow | None:
    """Pull the 'Aggregated' row out of a Locust _stats.csv."""
    users_match = re.search(r"scale_(\d+)_stats\.csv$", os.path.basename(path))
    users = int(users_match.group(1)) if users_match else 0
    with open(path, newline="") as fh:
        for row in csv.DictReader(fh):
            if row.get("Name") == "Aggregated":
                return ScaleRow(
                    users=users,
                    requests=int(row["Request Count"]),
                    failures=int(row["Failure Count"]),
                    rps=float(row["Requests/s"]),
                    p50_ms=float(row["50%"]),
                    p95_ms=float(row["95%"]),
                    p99_ms=float(row["99%"]),
                )
    return None


def _collect_scales(outdir: str) -> list[ScaleRow]:
    rows = [
        _parse_scale_csv(p) for p in sorted(glob.glob(os.path.join(outdir, "scale_*_stats.csv")))
    ]
    return sorted((r for r in rows if r is not None), key=lambda r: r.users)


def _query_llm_cost(workspace_guid: str, since: str) -> dict[str, float] | None:
    """Best-effort App Insights query for the real-burst LLM spend. Returns
    None if az is unavailable or the query fails (the operator can fill the
    numbers from the Workbook instead)."""
    kql = (
        "AppDependencies "
        f"| where TimeGenerated > ago({since}) "
        '| where Name startswith "llm." '
        "| summarize spans=count(), "
        'total_tokens=sum(toint(Properties["llm.total_tokens"])), '
        'total_cost=sum(todouble(Properties["llm.total_cost_usd"]))'
    )
    try:
        out = subprocess.run(
            [
                "az",
                "monitor",
                "log-analytics",
                "query",
                "-w",
                workspace_guid,
                "--analytics-query",
                kql,
                "-o",
                "json",
            ],
            capture_output=True,
            text=True,
            timeout=120,
            check=True,
        )
    except (subprocess.SubprocessError, FileNotFoundError) as exc:
        print(f"  (skipping App Insights query: {exc})", file=sys.stderr)
        return None
    try:
        rows = json.loads(out.stdout)
    except json.JSONDecodeError:
        return None
    if not rows:
        return {"spans": 0.0, "total_tokens": 0.0, "total_cost": 0.0}
    r = rows[0]
    return {
        "spans": float(r.get("spans", 0) or 0),
        "total_tokens": float(r.get("total_tokens", 0) or 0),
        "total_cost": float(r.get("total_cost", 0) or 0),
    }


def _render(scales: list[ScaleRow], llm: dict[str, float] | None) -> str:
    lines: list[str] = []
    lines.append("# Step 11 — Load Test Results\n")
    lines.append(
        "> Generated by `scripts/analyze_load_test.py`. Infra numbers are from the "
        "**mock-LLM** scaling run (Azure OpenAI held constant so scaling is isolated); "
        "the cost/latency row is from the **tiny real burst**. The two are never "
        "conflated.\n"
    )

    lines.append("## Infra scaling (mock-LLM run)\n")
    if scales:
        lines.append(
            "| Users | Requests | Failures | Failure % | RPS | P50 (ms) | P95 (ms) | P99 (ms) |"
        )
        lines.append("|---|---|---|---|---|---|---|---|")
        for s in scales:
            lines.append(
                f"| {s.users} | {s.requests} | {s.failures} | {s.failure_pct:.2f}% | "
                f"{s.rps:.1f} | {s.p50_ms:.0f} | {s.p95_ms:.0f} | {s.p99_ms:.0f} |"
            )
        lines.append("")
    else:
        lines.append(
            "_No `scale_*_stats.csv` found in the outdir — run `scripts/run_load_tests.sh` first._\n"
        )

    lines.append("## Real-burst LLM cost (App Insights)\n")
    if llm is not None:
        runs = "n/a"
        cost_per = "n/a"
        if llm["spans"]:
            lines.append(
                f"- Spans: **{int(llm['spans'])}** · Tokens: **{int(llm['total_tokens']):,}** · "
                f"Cost: **${llm['total_cost']:.4f}**\n"
            )
        else:
            lines.append(
                "- No `llm.*` spans in the window yet (run the real burst, mind ingestion lag).\n"
            )
        _ = (runs, cost_per)
    else:
        lines.append(
            "- _App Insights not queried (pass `--workspace-guid`); fill from the Cost & Tokens Workbook._\n"
        )

    lines.append("## Findings (fill from the run)\n")
    lines.append(
        "- **Scaling:** KEDA scaled worker pods 0→N on queue depth; HPA scaled API pods on CPU; cluster-autoscaler nodes <N1→N2> in <S>s. *(from `kubectl get hpa,pods,nodes` screenshots)*"
    )
    lines.append(
        "- **Bottleneck:** the LLM backend is **10K-TPM-bound by design** — the queue + KEDA turn that ceiling into backpressure (workers drain at a quota-safe rate) instead of a cascade of 429s."
    )
    lines.append(
        "- **At 10x:** raise Azure OpenAI TPM quota; the async/queue architecture already absorbs the burst — scale `maxReplicaCount` + node pool; consider a Premium Service Bus + dead-letter monitoring."
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Summarise the Step-11 load test.")
    ap.add_argument("--outdir", default=DEFAULT_OUTDIR, help="dir with scale_*_stats.csv")
    ap.add_argument("--report", default=DEFAULT_REPORT, help="output Markdown path")
    ap.add_argument(
        "--workspace-guid", default=None, help="log-aaf-dev customerId to query LLM cost"
    )
    ap.add_argument("--burst-since", default="1h", help="KQL ago() window for the real burst")
    args = ap.parse_args()

    scales = _collect_scales(args.outdir)
    llm = None
    if args.workspace_guid:
        llm = _query_llm_cost(args.workspace_guid, args.burst_since)

    report = _render(scales, llm)
    with open(args.report, "w") as fh:
        fh.write(report)
    print(f"wrote {args.report} ({len(scales)} scale points)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
